# Reference presets that should apply to this repository
presets:
  - dockerfile
  - renovate
  - workflows-default

workflows:
  check:
    inputs:
      image: wetransform/nginx-metrics
  publish:
    inputs:
      image: wetransform/nginx-metrics
  release:
    inputs:
      image: wetransform/nginx-metrics

# List of custom required checks
required_checks:
  - test / check / run
